### ISSUE TITLE
Epic 1: Core Backend Infrastructure Setup

### ISSUE THREAD

**Issue by rabble** [rabble/nostrvine#31]
# Epic 1: Core Backend Infrastructure Setup

## Overview
Set up the foundational Cloudflare Workers infrastructure for the NostrVine CDN solution using Pattern A (Cloudflare Stream-centric).

## Acceptance Criteria
- [ ] Cloudflare Workers project initialized with proper structure
- [ ] `wrangler.toml` configured with `dev` and `prod` environments with `nodejs_compat` flag
- [ ] KV namespace `VIDEO_STATUS_KV` created and bound to workers
- [ ] Secrets configured for Cloudflare API Token and Stream Webhook
- [ ] Cloudflare Stream enabled on account
- [ ] Cloudflare Images configured to source from Stream delivery domain
- [ ] VideoStatus JSON schema formally documented

### Project Structure
```
backend/
├── wrangler.toml
├── package.json
├── src/
│   ├── index.js (main router)
│   ├── upload-request-worker.js
│   ├── webhook-handler-worker.js
│   ├── status-check-worker.js
│   └── lib/
│       ├── auth.js (NIP-98 validation using nostr-tools)
│       ├── types.js (data models)
│       └── schemas.js (JSON schemas)
```

### wrangler.toml Configuration
```toml
name = "nostrvine-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.dev]
kv_namespaces = [
  { binding = "VIDEO_STATUS_KV", id = "dev_video_status" }
]

[env.prod]
kv_namespaces = [
  { binding = "VIDEO_STATUS_KV", id = "prod_video_status" }
]

[[env.dev.routes]]
pattern = "api-dev.nostrvine.com/*"

[[env.prod.routes]]
pattern = "api.nostrvine.com/*"
```

### Required Secrets
- `CLOUDFLARE_API_TOKEN`: For Stream API calls
- `STREAM_WEBHOOK_SECRET`: For webhook signature validation
- `STREAM_ACCOUNT_ID`: Cloudflare account ID
- `CLOUDFLARE_IMAGES_ACCOUNT_HASH`: For Images URL transformation

### VideoStatus JSON Schema (src/lib/schemas.js)
```javascript
export const VideoStatusSchema = {
  type: "object",
  required: ["videoId", "nostrPubkey", "status", "createdAt", "updatedAt"],
  properties: {
    videoId: { type: "string", format: "uuid" },
    nostrPubkey: { type: "string", pattern: "^[0-9a-f]{64}$" },
    status: { 
      type: "string", 
      enum: ["pending_upload", "processing", "published", "quarantined", "failed"] 
    },
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
    source: {
      type: "object",
      properties: {
        uploadedAt: { type: "string", format: "date-time", nullable: true },
        error: { type: "string", nullable: true }
      }
    },
    stream: {
      type: "object",
      properties: {
        uid: { type: "string" },
        hlsUrl: { type: "string", format: "uri", nullable: true },
        dashUrl: { type: "string", format: "uri", nullable: true },
        thumbnailUrl: { type: "string", format: "uri", nullable: true }
      }
    },
    moderation: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["pending", "approved", "rejected"] },
        flaggedCategories: { type: "array", items: { type: "string" } },
        checkedAt: { type: "string", format: "date-time", nullable: true }
      }
    }
  }
};
```

### Package.json Dependencies
```json
{
  "name": "nostrvine-api",
  "version": "1.0.0",
  "dependencies": {
    "nostr-tools": "^2.7.0"
  },
  "devDependencies": {
    "wrangler": "^3.78.0",
    "miniflare": "^3.20240925.0"
  }
}
```

## Testing
- [ ] Local development environment works with `wrangler dev`
- [ ] KV namespace accessible in dev environment
- [ ] Secrets properly configured and accessible
- [ ] Stream API connection verified
- [ ] nostr-tools signature verification working

## Dependencies
- Cloudflare account with Workers, KV, Stream, and Images enabled
- Domain configured for API endpoints
- Development environment with wrangler CLI

## Definition of Done
- All infrastructure components are provisioned and configured
- Local development environment is fully functional
- Configuration is documented and version controlled
- Secrets are properly managed (not committed to repo)
- VideoStatus schema is documented and validated
